Use datatable column descriptions from server-side
UpstreamDataInc/goosebit pull request #215
Opened 2024-11-26 16:35 UTC by b-rowan

A continuation of the server-side column handling introduced in #170, handling for the devices page is now slightly cleaner, and handling has been introduced for the remaining pages.

2024-12-01 11:09 UTC, tsagadar requested changes
Great to have this functionality unified in all screens. It comes with an additional request to show the UI (vs. embedding a column config already during template generation) but this should not really matter.

2024-12-02 19:56 UTC, b-rowan commented on goosebit/ui/static/js/software.js
> +                downloadSoftware(selectedSoftware[0]);
This is not doing what you think.  `selectedSoftware` is an array of objects representing the software in the `SoftwareSchema` format, which is then mapped to be an array of the `id` value.  This is grabbing the first software instance in that array (which in this case is just the id) to download.

2024-12-02 19:56 UTC, b-rowan commented on goosebit/ui/static/js/software.js
> +                downloadSoftware(selectedSoftware[0]);
Hence the line 
```
                    .map((d) => d.id);
```

2024-12-03 07:19 UTC, tsagadar commented on goosebit/ui/static/js/software.js
> +                downloadSoftware(selectedSoftware[0]);
Correct - sorry for that.

2024-12-03 07:19 UTC, tsagadar approved these changes

2024-12-03 16:34 UTC, merged